<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="2" tests="3" time="30.36">
 <testsuite name="Logon M4Nodejs Suite" timestamp="2020-03-03T12:53:33" hostname="localhost" time="30.36" errors="0" tests="3" skipped="0" disabled="0" failures="2">
  <testcase classname="Logon M4Nodejs Suite" name="Should create an instance" time="0.001" />
  <testcase classname="Logon M4Nodejs Suite" name="Should do logon" time="30.021">
   <failure type="exception" message="Error: Timeout - Async function did not complete within 30000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)"><![CDATA[Error: Timeout - Async function did not complete within 30000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
    at <Jasmine>
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)]]>
   </failure>
  </testcase>
  <testcase classname="Logon M4Nodejs Suite" name="Should load employee name" time="0.084">
   <failure type="exception" message="[object Object] thrown"><![CDATA[[object Object] thrown]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>