<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="1" tests="3" time="2.597">
 <testsuite name="Logon M4Nodejs Suite Pila" timestamp="2020-03-04T11:02:29" hostname="localhost" time="2.597" errors="0" tests="3" skipped="0" disabled="0" failures="1">
  <testcase classname="Logon M4Nodejs Suite Pila" name="Should create an instance" time="0.001" />
  <testcase classname="Logon M4Nodejs Suite Pila" name="Should do logon" time="0.368" />
  <testcase classname="Logon M4Nodejs Suite Pila" name="Should execute Colombia Pila" time="2.016">
   <failure type="exception" message="Error setting item &lt;SCB_P_FECHA_EFECTIVA&gt; value: Invalid date/time value: &quot;01/11/2019&quot; for item SCB_P_FECHA_EFECTIVA thrown"><![CDATA[Error setting item <SCB_P_FECHA_EFECTIVA> value: Invalid date/time value: "01/11/2019" for item SCB_P_FECHA_EFECTIVA thrown]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>