<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="1" tests="3" time="0.722">
 <testsuite name="Logon M4Nodejs Suite" timestamp="2020-03-03T14:40:18" hostname="localhost" time="0.722" errors="0" tests="3" skipped="0" disabled="0" failures="1">
  <testcase classname="Logon M4Nodejs Suite" name="Should create an instance" time="0" />
  <testcase classname="Logon M4Nodejs Suite" name="Should do logon" time="0.407" />
  <testcase classname="Logon M4Nodejs Suite" name="Should load employee name" time="0.084">
   <failure type="exception" message="[object Object] thrown"><![CDATA[[object Object] thrown]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>